name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run tests (Neovim ${{ matrix.nvim_version }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        nvim_version: [stable, nightly]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.nvim_version }}

      - name: Install plenary.nvim
        run: |
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim \
            /tmp/plenary.nvim

      - name: Run tests
        run: |
          PLENARY_PATH=/tmp/plenary.nvim ./scripts/test.sh
